// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR8HUGSg6oRiO6nvVAIlkYLINBfUVCcy4',
    appId: '1:653270463909:web:161e2f5d98da95892fa44c',
    messagingSenderId: '653270463909',
    projectId: 'financeapp-a0be3',
    authDomain: 'financeapp-a0be3.firebaseapp.com',
    storageBucket: 'financeapp-a0be3.firebasestorage.app',
    measurementId: 'G-ED365RNFRS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn31diD9TiG5rbFz251ILgxhf_vp_nTyk',
    appId: '1:653270463909:android:1f2a008b701610de2fa44c',
    messagingSenderId: '653270463909',
    projectId: 'financeapp-a0be3',
    storageBucket: 'financeapp-a0be3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCygTJnJOuojFGhcYv6ia8zjdhsgzqtyq4',
    appId: '1:653270463909:ios:9a4d880cb8b32b152fa44c',
    messagingSenderId: '653270463909',
    projectId: 'financeapp-a0be3',
    storageBucket: 'financeapp-a0be3.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCygTJnJOuojFGhcYv6ia8zjdhsgzqtyq4',
    appId: '1:653270463909:ios:9a4d880cb8b32b152fa44c',
    messagingSenderId: '653270463909',
    projectId: 'financeapp-a0be3',
    storageBucket: 'financeapp-a0be3.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR8HUGSg6oRiO6nvVAIlkYLINBfUVCcy4',
    appId: '1:653270463909:web:a2de7f25e9f161e72fa44c',
    messagingSenderId: '653270463909',
    projectId: 'financeapp-a0be3',
    authDomain: 'financeapp-a0be3.firebaseapp.com',
    storageBucket: 'financeapp-a0be3.firebasestorage.app',
    measurementId: 'G-8MXJD8BY3R',
  );
}
